"""
Interpretation Layer - Phụ Tinh Meanings (Complete)
All auxiliary star meanings with nature and effects
"""

PHU_TINH_MEANINGS = {
    # === LỤC CÁT TINH ===
    'Tả Phụ': {'nature': 'Cát', 'effect': 'Có quý nhân phò tá, được giúp đỡ, có người hỗ trợ bên trái'},
    'Hữu Bật': {'nature': 'Cát', 'effect': 'Có người hỗ trợ bên phải, công việc thuận lợi'},
    'Văn Xương': {'nature': 'Cát', 'effect': 'Thông minh, có tài văn chương, học hành giỏi'},
    'Văn Khúc': {'nature': 'Cát', 'effect': 'Khéo léo, có tài nghệ thuật, đa tài'},
    'Thiên Khôi': {'nature': 'Cát', 'effect': 'Có quý nhân nam giúp đỡ, gặp người tốt'},
    'Thiên Việt': {'nature': 'Cát', 'effect': 'Có quý nhân nữ phù trợ, được nâng đỡ'},
    
    # === LỤC SÁT TINH ===
    'Kinh Dương': {'nature': 'Sát', 'effect': 'Cứng rắn, dễ xung đột, gặp tai nạn, bất hòa'},
    'Đà La': {'nature': 'Sát', 'effect': 'Trì trệ, chậm trễ, hay lo âu, khó tiến'},
    'Hỏa Tinh': {'nature': 'Sát', 'effect': 'Nóng nảy, vội vàng, dễ mất mát, tai họa bất ngờ'},
    'Linh Tinh': {'nature': 'Sát', 'effect': 'Bất ổn, hay thay đổi, cô độc, không yên'},
    'Địa Không': {'nature': 'Sát', 'effect': 'Hao tài, mất mát, bất an, trống rỗng'},
    'Địa Kiếp': {'nature': 'Sát', 'effect': 'Tổn thất, biến cố, tai họa, kiếp nạn'},
    
    # === 12 TRƯỜNG SINH ===
    'Trường Sinh': {'nature': 'Cát', 'effect': 'Phát triển tốt, khởi đầu thuận lợi, trường thọ'},
    'Mộc Dục': {'nature': 'Trung', 'effect': 'Giai đoạn phát triển, cần che chở, đào hoa'},
    'Quan Đới': {'nature': 'Cát', 'effect': 'Trưởng thành, có địa vị, được tôn trọng'},
    'Lâm Quan': {'nature': 'Cát', 'effect': 'Có chức vị, được đề bạt, thăng tiến'},
    'Đế Vượng': {'nature': 'Đại Cát', 'effect': 'Hưng vượng, thành công đỉnh cao, vinh hiển'},
    'Suy': {'nature': 'Hung', 'effect': 'Bắt đầu suy giảm, cần cẩn thận'},
    'Bệnh': {'nature': 'Hung', 'effect': 'Sức khỏe yếu, dễ ốm đau, trở ngại'},
    'Tử': {'nature': 'Hung', 'effect': 'Suy yếu, khó khăn, kết thúc chu kỳ'},
    'Mộ': {'nature': 'Trung', 'effect': 'Ẩn tàng, tiềm lực chưa phát, cất giữ'},
    'Tuyệt': {'nature': 'Hung', 'effect': 'Giai đoạn thấp nhất, cần phục hồi'},
    'Thai': {'nature': 'Trung', 'effect': 'Mới bắt đầu, còn non nớt, thai nghén'},
    'Dưỡng': {'nature': 'Cát', 'effect': 'Nuôi dưỡng, phát triển dần, được chăm sóc'},
    
    # === 12 BÁC SĨ VÒNG ===
    'Bác Sĩ': {'nature': 'Cát', 'effect': 'Thông minh, có học thức, tài năng'},
    'Lục Sĩ': {'nature': 'Cát', 'effect': 'Có sức mạnh, can đảm, quyền lực'},
    'Thanh Long': {'nature': 'Cát', 'effect': 'May mắn, vui vẻ, tin tốt lành'},
    'Tiểu Hao': {'nature': 'Hung', 'effect': 'Hao tài nhỏ, chi tiêu, mất mát'},
    'Tướng Quân': {'nature': 'Cát', 'effect': 'Có quyền uy, lãnh đạo, dũng cảm'},
    'Tàu Thu': {'nature': 'Cát', 'effect': 'Giấy tờ suôn sẻ, tin tức tốt'},
    'Phi Liêm': {'nature': 'Hung', 'effect': 'Thị phi, kiện tụng, rắc rối'},
    'Hỉ Thần': {'nature': 'Cát', 'effect': 'Vui mừng, hỷ sự, may mắn'},
    'Bệnh Phù': {'nature': 'Hung', 'effect': 'Bệnh tật, ốm đau, sức khỏe kém'},
    'Đại Hao': {'nature': 'Hung', 'effect': 'Hao tài lớn, tổn thất nặng'},
    'Phúc Bình': {'nature': 'Hung', 'effect': 'Tiểu nhân, kẻ thù ngầm, phản bội'},
    'Quan Phù': {'nature': 'Hung', 'effect': 'Kiện tụng, quan tụng, rắc rối pháp lý'},
    
    # === 12 THÁI TUẾ VÒNG ===
    'Thái Tuế': {'nature': 'Hung', 'effect': 'Năm hạn, cần cẩn thận, biến động'},
    'Thiếu Dương': {'nature': 'Cát', 'effect': 'Quý nhân nam trẻ, may mắn'},
    'Tang Môn': {'nature': 'Hung', 'effect': 'Tang tóc, buồn phiền, mất mát'},
    'Thiếu Âm': {'nature': 'Cát', 'effect': 'Quý nhân nữ trẻ, được giúp đỡ'},
    'Từ Phù': {'nature': 'Hung', 'effect': 'May rủi, cần cẩn thận'},
    'Tuế Phá': {'nature': 'Hung', 'effect': 'Phá tán, mất mát, hao tổn'},
    'Long Đức': {'nature': 'Cát', 'effect': 'Phúc đức, may mắn, được phù hộ'},
    'Bạch Hổ': {'nature': 'Hung', 'effect': 'Tai nạn, máu huyết, nguy hiểm'},
    'Phúc Đức': {'nature': 'Cát', 'effect': 'Phúc phần, may mắn, an lành'},
    'Điếu Khách': {'nature': 'Hung', 'effect': 'Tang tóc, chia ly, buồn phiền'},
    'Trực Phù': {'nature': 'Trung', 'effect': 'Đi thẳng, cương trực, không uyển chuyển'},
    
    # === SAO KHÁC ===
    'Lộc Tồn': {'nature': 'Đại Cát', 'effect': 'Giàu có, no đủ, tài lộc dồi dào, không lo ăn mặc'},
    'Thiên Mã': {'nature': 'Cát', 'effect': 'Di chuyển nhiều, năng động, phát triển, thay đổi'},
    'Hồng Loan': {'nature': 'Đào Hoa', 'effect': 'Có duyên, gặp người tâm đầu ý hợp, hôn nhân'},
    'Thiên Hỹ': {'nature': 'Cát', 'effect': 'Vui vẻ, có tin vui, sung sướng, hỷ sự'},
    'Đào Hoa': {'nature': 'Đào Hoa', 'effect': 'Có sức hút, duyên dáng, lãng mạn'},
    'Hoa Cái': {'nature': 'Trung', 'effect': 'Nghệ thuật, cô đơn cao quý, độc đáo'},
    'Thiên Quan': {'nature': 'Cát', 'effect': 'Có quyền chức, được thăng tiến, quan lộc'},
    'Thiên Phúc': {'nature': 'Cát', 'effect': 'Có phúc, gặp may mắn, được che chở'},
    'Thiên Thường': {'nature': 'Hung', 'effect': 'Thương tích, tai nạn, đau đớn'},
    'Thiên Sứ': {'nature': 'Hung', 'effect': 'Bệnh tật, sức khỏe kém'},
    'Phong Cáo': {'nature': 'Cát', 'effect': 'Được khen ngợi, danh tiếng, vinh dự'},
    'Quốc Ấn': {'nature': 'Cát', 'effect': 'Quyền lực, chức vị, được tín nhiệm'},
    'Đường Phù': {'nature': 'Cát', 'effect': 'Giấy tờ thuận lợi, được bảo hộ'},
    'Thiên Thọ': {'nature': 'Cát', 'effect': 'Trường thọ, sức khỏe tốt'},
    'Thiên Tài': {'nature': 'Cát', 'effect': 'Có tài năng riêng, giỏi giang'},
    'Thiên Diêu': {'nature': 'Đào Hoa', 'effect': 'Quyến rũ, thu hút, lãng mạn'},
    'Thiên La': {'nature': 'Hung', 'effect': 'Bị ràng buộc, khó thoát, trở ngại'},
    'Địa Võng': {'nature': 'Hung', 'effect': 'Bị mắc kẹt, khó khăn, vướng mắc'},
    'Ân Quang': {'nature': 'Cát', 'effect': 'Được ân sủng, may mắn, quý nhân'},
    'Thiên Quý': {'nature': 'Cát', 'effect': 'Quý nhân phù hộ, được nâng đỡ'},
    'Thiên Hình': {'nature': 'Hung', 'effect': 'Hình phạt, kiện tụng, xung đột'},
    'Tam Thai': {'nature': 'Cát', 'effect': 'Quan lộc, chức vị, thành đạt'},
    'Bát Tọa': {'nature': 'Cát', 'effect': 'Địa vị vững, ổn định, được tôn trọng'},
    'Thiên Trù': {'nature': 'Cát', 'effect': 'Không lo ăn uống, sung túc'},
    'Thiên Khốc': {'nature': 'Hung', 'effect': 'Buồn khóc, đau khổ, thương tâm'},
    'Thiên Hư': {'nature': 'Hung', 'effect': 'Hư hao, mất mát, trống rỗng'},
    'L.Long Đức': {'nature': 'Cát', 'effect': 'Phúc đức theo tháng, may mắn'},
    'L.Nguyệt Đức': {'nature': 'Cát', 'effect': 'Phúc đức theo tháng, được bảo hộ'},
    
    # === TUẦN TRIỆT VÀ SAO MỚI BỔ SUNG ===
    'Tuần 1': {'nature': 'Đặc biệt', 'effect': 'Cung bị Tuần - sao trong cung bị giảm lực, có thể hóa giải hung tinh'},
    'Tuần 2': {'nature': 'Đặc biệt', 'effect': 'Cung bị Tuần - sao trong cung bị giảm lực, có thể hóa giải hung tinh'},
    'Triệt 1': {'nature': 'Đặc biệt', 'effect': 'Cung bị Triệt - sao bị cắt đứt lực, ảnh hưởng Đại Hạn'},
    'Triệt 2': {'nature': 'Đặc biệt', 'effect': 'Cung bị Triệt - sao bị cắt đứt lực, ảnh hưởng Đại Hạn'},
    'Cô Thần': {'nature': 'Hung', 'effect': 'Cô đơn, ít được giúp đỡ, tự lập (Nam dùng)'},
    'Quả Tú': {'nature': 'Hung', 'effect': 'Cô độc, khó có bạn đời, góa bụa (Nữ dùng)'},
    'Thái Phụ': {'nature': 'Đào Hoa', 'effect': 'Duyên dáng, quyến rũ, có sức hút với người khác giới'},
    'Phong Các': {'nature': 'Cát', 'effect': 'Tài hoa, nghệ thuật, thanh nhã, quý phái'},
    'Giải Thần': {'nature': 'Cát', 'effect': 'Hóa giải hung tinh, tránh được tai họa'},
    'Thiên Giải': {'nature': 'Cát', 'effect': 'Được cứu giải khỏi tai nạn, may mắn thoát hiểm'},
    'Thiên Đức': {'nature': 'Cát', 'effect': 'Có đức, được phù hộ, tránh được nhiều tai họa'},
    'Nguyệt Đức': {'nature': 'Cát', 'effect': 'Có đức, được bảo hộ, gặp hung hóa cát'},
    'Lưu Hà': {'nature': 'Hung', 'effect': 'Tai nạn sông nước, cẩn thận khi di chuyển gần nước'},
    'Thiên Y': {'nature': 'Cát', 'effect': 'Có duyên với y thuật, chữa bệnh, được chữa khỏi bệnh'},
    'Kiếp Sát': {'nature': 'Hung', 'effect': 'Kiếp nạn, tai họa bất ngờ, cần đề phòng'},
    'Phá Toái': {'nature': 'Hung', 'effect': 'Phá tan, hao tán, sự việc không thành'},
    'Thiên Vu': {'nature': 'Hung', 'effect': 'Khóc lóc, buồn phiền, tang tóc'},
    'Thiên Tài (Năm)': {'nature': 'Cát', 'effect': 'Tài năng thiên phú theo năm sinh'},
    'Thiên Thọ (Năm)': {'nature': 'Cát', 'effect': 'Trường thọ theo năm sinh'},
}
